name: frontend
version: 0.0.1
description: Regatta frontend
author:
homepage: https://regatta.atlassian.net
documentation:

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  angular2: any
  angular2_components: any
  browser: any
  dart_to_js_script_rewriter: any
  dson: any
  greencat: any
  http: any
  stream_transformers: any
  sass_transformer: any
  reflectable: any

dev_dependencies:
  dart_style: any
  test: any
  pageloader: any
  quiver: any
  mockito: any

transformers:
  - angular2/transform/codegen:
      platform_directives:
        - package:angular2/common.dart#COMMON_DIRECTIVES
      platform_pipes:
        - 'package:angular2/common.dart#COMMON_PIPES'
      entry_points: web/main.dart
      resolved_identifiers:
        BrowserClient: 'package:http/browser_client.dart'
        Client: 'package:http/http.dart'
  - angular2/transform/reflection_remover:
      $include:
        - test/**_test.dart
        - web/main.dart
  - reflectable:
      entry_points:
        - web/main.dart
      formatted: true
  - test/pub_serve:
      $include: test/**_test.dart
  - dart_to_js_script_rewriter
  - sass_transformer
