name: frontend
description: Regatta frontend
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.22
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  http: ^0.11.0
  stream_transformers: ^0.3.0
  ng_bootstrap: 0.4.0
  sass_transformer: any
  reflectable: any
transformers:
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
- reflectable:
    entry_points:
      - web/main.dart
    formatted: true
- $dart2js:
   environment: {hostname: 'http://localhost:8000'}
- dart_to_js_script_rewriter
- sass_transformer
