language: python

python:
  - "3.4"
  - "3.5"

install:
  - travis_retry pip install -r regatta/requirements.txt
  - travis_retry pip install coveralls

script:
  - (cd regatta && python setup.py test)

after_success:
  - coveralls
