language: python

python:
  - "3.4"
  - "3.5"

install:
  - travis_retry pip install -r backend/requirements.txt
  - travis_retry pip install coveralls
  - travis_retry pip install flake8

before_script:
  - (cd backend && python setup.py flake8)

script:
  - (cd backend && coverage run setup.py test)

after_success:
  - (cd backend && coveralls)
