sudo: required
dist: trusty

language: python

python:
  - "3.4"
  - "3.5"

install:
  #- sudo apt-get update
  #- sudo apt-get install apt-transport-https
  # Travis specific install
  - sudo sh -c 'curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -'
  - sudo sh -c 'curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
  - sudo apt-get update
  - sudo apt-get install dart
  - export PATH=$PATH:/usr/lib/dart/bin
  # General install
  - (cd backend  && make env)
  - (cd backend  && make install_tools)
  - (cd backend  && make install)
  - (cd frontend && make install)
  # Prepare e2e test tools
  - (cd e2e_tests  && make install)

before_script:
  # Static analysis
  - (cd backend  && make lint)
  - (cd frontend && make lint)
  - (cd frontend && make style)
  # e2e tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - (cd backend   && make run > django-server.log 2>&1 &)
  - (cd frontend  && make run > angular-server.log 2>&1 &)
  - (cd e2e_tests && run > webdriver.log 2>&1 &)

script:
  - (cd backend   && make tests)
  - (cd frontend  && make tests)
  - (cd e2e_tests && make tests)

after_success:
  - (cd backend && coveralls)

after_script:
  - (cd backend && cat django-server.log)
  - (cd frontend && cat angular-server.log)
  - (cd e2e_tests && cat webdriver.log)
